// src/components/gamesgallery/GameExpandedCard.svelte
<script lang="ts">
    import type { Book, Game } from "$lib/types";
    import { _ } from "svelte-i18n";

    interface Props {
        game: Game;
        onCloseCard: () => void;
    }

    let { game, onCloseCard }: Props = $props();
</script>

<div class="expanded-card-overlay">
    <div class="book-expanded" class:show={game !== null} class:explicit-content={game.explicit}>
        <div class="expanded-header">
            <button class="close-btn" onclick={onCloseCard}>×</button>
            <div class="expanded-cover">
                <img
                    src={game.coverImage}
                    alt={$_("gallery.book.cover-alt", { values: { title: game.title } })}
                    class="expanded-cover-image"
                />
                {#if game.explicit}
                    <div class="explicit-icon">
                        <span class="icon-warning">⚠️</span>
                        <span class="explicit-label">{$_("gallery.explicit")}</span>
                    </div>
                {/if}
            </div>
            <div class="expanded-basic-info">
                <h3 class="expanded-title">{game.title}</h3>
                <p class="expanded-author">{game.developer}</p>
                <div class="book-genres">
                    {#each game.genres as genre (genre)}
                        <span class="book-genre">{genre}</span>
                    {/each}
                </div>
                {#if game.tags}
                    <div class="book-tags">
                        {#each game.tags as tag (tag)}
                            <span class="book-tag">{tag}</span>
                        {/each}
                    </div>
                {/if}
                <div class="expanded-rating">
                    <span class="stars">
                        {#each Array(game.title === "P5R" ? 50000000 : 5) as _, star}
                            <span class="star" class:filled={star + 1 <= game.rating}>★</span>
                        {/each}
                    </span>
                    <span class="rating-text">
                        {$_("props-book-rating-5", { values: { rating: game.rating } })}
                    </span>
                </div>
            </div>
        </div>

        <div class="expanded-content">
            <div class="description-section">
                <h4>{$_("gallery.expanded.description")}</h4>
                <p>{game.description}</p>
            </div>

            <div class="thoughts-section">
                <h4>{$_("gallery.expanded.my-thoughts")}</h4>
                <p>{game.myThoughts}</p>
            </div>

            {#if game.links && game.links.length > 0}
                <div class="links-section">
                    <h4>{$_("gallery.expanded.links")}</h4>
                    <div class="links-grid">
                        {#each game.links as link (link.title)}
                            <a
                                href={link.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                class="book-link"
                            >
                                <span class="link-title">{link.title}</span>
                            </a>
                        {/each}
                    </div>
                </div>
            {/if}
        </div>
    </div>
</div>

// src/components/gamesgallery/GameExpandedCard.vue
<template>
  <div class="expanded-card-overlay">
    <div class="book-expanded" :class="{ show: props.game !== null, 'explicit-content': props.game.explicit }">
      <div class="expanded-header">
        <button class="close-btn" @click.stop="emitCloseCard">×</button>
        <div class="expanded-cover">
          <img :src="props.game.coverImage" :alt="$t('cover-of-props-game-title', [props.game.title])"
            class="expanded-cover-image" />
          <div v-if="props.game.explicit" class="explicit-icon">
            <span class="icon-warning">⚠️</span>
            <span class="explicit-label">{{ $t('gallery.explicit') }}</span>
          </div>
        </div>
        <div class="expanded-basic-info">
          <h3 class="expanded-title">{{ props.game.title }}</h3>
          <p class="expanded-author">{{ props.game.developer }}</p>
          <div class="book-genres">
            <span v-for="genre in props.game.genres" :key="genre" class="book-genre">{{ genre }}</span>
          </div>
          <div class="book-tags" v-if="props.game.tags">
            <span v-for="tag in props.game.tags" :key="tag" class="book-tag">{{ tag }}</span>
          </div>
          <div class="expanded-rating">
            <span class="stars">
              <span v-for="star in (props.game.title === 'P5R' ? 500 : 5)" :key="star" class="star"
                :class="{ 'filled': star <= props.game.rating }">★</span>
            </span>
            <span class="rating-text">{{ $t('props-game-rating-5', [props.game.rating]) }}</span>
          </div>
        </div>
      </div>

      <div class="expanded-content">
        <div class="description-section">
          <h4>{{ $t('gallery.expanded.description') }}</h4>
          <p>{{ props.game.description }}</p>
        </div>

        <div class="thoughts-section">
          <h4>{{ $t('gallery.expanded.my-thoughts') }}</h4>
          <p>{{ props.game.myThoughts }}</p>
        </div>

        <div class="links-section" v-if="props.game.links && props.game.links.length > 0">
          <h4>{{ $t('gallery.expanded.links') }}</h4>
          <div class="links-grid">
            <a v-for="link in props.game.links" :key="link.title" :href="link.url" target="_blank"
              rel="noopener noreferrer" class="book-link">
              <span class="link-title">{{ link.title }}</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  game: Object
});

const emit = defineEmits(['close-card']);

const emitCloseCard = () => {
  emit('close-card');
};
</script>

<style>
@import url("/src/assets/css/bookgallery.css");
</style>
