// app/components/gallery/MultiSelectDropdown.vue
<template>
    <div class="multi-select" ref="dropdownRef">
        <label>{{ label }}:</label>
        <div class="dropdown" @click.stop="emitToggle" :class="{ open: isOpen }" tabindex="0" @blur="emitClose">
            <div class="dropdown-selected">
                <span v-if="selectedItems.length === 0" class="placeholder">{{ placeholder }}</span>
                <span v-else class="selected-items">{{ selectedItems.join(", ") }}</span>
                <span class="dropdown-arrow">▾</span>
            </div>
            <ul class="dropdown-list" v-if="isOpen">
                <li v-for="item in items" :key="item.value" :class="{ selected: selectedItems.includes(item.value) }"
                    @click.stop="emitItemToggle(item.value)">
                    <input type="checkbox" :checked="selectedItems.includes(item.value)" readonly />
                    {{ item.value }} <span v-if="item.count" class="tag-count">({{ item.count }})</span>
                </li>
                <li v-if="items.length === 0 && selectedItems.length === 0" class="no-tags">
                    {{ noItemsMessage }}
                </li>
            </ul>
        </div>
    </div>
</template>

<script setup>
defineProps({
    label: String,
    items: Array,
    selectedItems: Array,
    placeholder: String,
    noItemsMessage: String,
    isOpen: Boolean
});

const emit = defineEmits(['toggle', 'close', 'toggle-item']);

const emitToggle = () => emit('toggle');
const emitClose = () => emit('close');
const emitItemToggle = (itemValue) => emit('toggle-item', itemValue);
</script>

// src/components/gallery/MultiSelectDropdown.svelte
<script lang="ts">
    interface DropdownItem {
        value: string;
        count?: number;
    }

    interface Props {
        label: string;
        items: DropdownItem[];
        selectedItems: string[];
        placeholder: string;
        noItemsMessage: string;
        isOpen: boolean;
        ontoggle?: () => void;
        onclose?: () => void;
        "ontoggle-item"?: (itemValue: string) => void;
    }

    let {
        label,
        items,
        selectedItems,
        placeholder,
        noItemsMessage,
        isOpen,
        ontoggle,
        onclose,
        "ontoggle-item": onToggleItem
    }: Props = $props();

    let dropdownRef: HTMLDivElement;

    const handleToggle = () => {
        ontoggle?.();
    };

    const handleClose = () => {
        onclose?.();
    };

    const handleItemToggle = (itemValue: string) => {
        onToggleItem?.(itemValue);
    };

    const handleClick = (event: MouseEvent) => {
        event.stopPropagation();
        handleToggle();
    };

    const handleItemClick = (event: MouseEvent, itemValue: string) => {
        event.stopPropagation();
        handleItemToggle(itemValue);
    };
</script>

<div bind:this={dropdownRef} class="multi-select">
    <!-- svelte-ignore a11y_label_has_associated_control -->
    <label>{label}</label>
    <div
        class="dropdown"
        class:open={isOpen}
        tabindex="0"
        onmousedown={handleClick}
        onblur={handleClose}
        role="button"
    >
        <div class="dropdown-selected">
            {#if selectedItems.length === 0}
                <span class="placeholder">{placeholder}</span>
            {:else}
                <span class="selected-items">{selectedItems.join(", ")}</span>
            {/if}
            <span class="dropdown-arrow">▾</span>
        </div>
        {#if isOpen}
            <ul class="dropdown-list">
                {#each items as item (item.value)}
                    <li class:selected={selectedItems.includes(item.value)}>
                        <button
                            type="button"
                            class="dropdown-item-button"
                            onclick={(event) => handleItemClick(event, item.value)}
                        >
                            <input
                                type="checkbox"
                                checked={selectedItems.includes(item.value)}
                                readonly
                                tabindex="-1"
                            />
                            {item.value}
                            {#if item.count}
                                <span class="tag-count">{item.count}</span>
                            {/if}
                        </button>
                    </li>
                {/each}
                {#if items.length === 0 && selectedItems.length === 0}
                    <li class="no-tags">
                        {noItemsMessage}
                    </li>
                {/if}
            </ul>
        {/if}
    </div>
</div>
